In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [13]:
#Creating DataFreame
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [6]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [14]:
#Creating an instance of OneHotencoder
encoder=OneHotEncoder()

In [15]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [17]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [20]:
encoder.transform([['blue']]).toarray()

d:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [24]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [ ]:
#Work to do
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [27]:
lbl_encoder.fit_transform(df[['color']])

d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [29]:
lbl_encoder.transform([['red']])
lbl_encoder.transform([['blue']])
lbl_encoder.transform([['green']])

d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
d:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [30]:
#Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [31]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [32]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [33]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [35]:
encoder.transform([['small']])

d:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [1]:
#Target Guided Ordinal Encoding
import pandas as pd

df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [2]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [6]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [7]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [9]:
dataf=df['city_encoded']=df['city'].map(mean_price)

In [12]:
df[['city','city_encoded']]

       city  city_encoded
0  New York         190.0
1    London         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         190.0
5     Paris         310.0

In [16]:
import seaborn as sns
df=sns.load_dataset('tips')

In [17]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
mean_time=df.groupby('time')['total_bill'].mean()

C:\Users\siddh\AppData\Local\Temp\ipykernel_25388\1574852837.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_time=df.groupby('time')['total_bill'].mean()

In [23]:
mean_time

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [24]:
dataff=df['city_time']=df['time'].map(mean_time)

In [27]:
df[['time','city_time']]

       time  city_time
0    Dinner  20.797159
1    Dinner  20.797159
2    Dinner  20.797159
3    Dinner  20.797159
4    Dinner  20.797159
..      ...        ...
239  Dinner  20.797159
240  Dinner  20.797159
241  Dinner  20.797159
242  Dinner  20.797159
243  Dinner  20.797159

[244 rows x 2 columns]